; =============================================================================
; pjsip.conf — Transporte
; =============================================================================

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060
external_media_address = SEU_IP_PUBLICO
external_signaling_address = SEU_IP_PUBLICO
local_net = 10.0.0.0/16

[transport-tcp]
type = transport
protocol = tcp
bind = 0.0.0.0:5060
external_media_address = SEU_IP_PUBLICO
external_signaling_address = SEU_IP_PUBLICO
local_net = 10.0.0.0/16
